-- 가보자고 지역 테이블 더미 데이터
INSERT INTO GR(NAME)VALUES('강원');
INSERT INTO GR(NAME)VALUES('경기');
INSERT INTO GR(NAME)VALUES('경남');
INSERT INTO GR(NAME)VALUES('경북');
INSERT INTO GR(NAME)VALUES('광주');
INSERT INTO GR(NAME)VALUES('대구');
INSERT INTO GR(NAME)VALUES('대전');
INSERT INTO GR(NAME)VALUES('부산');
INSERT INTO GR(NAME)VALUES('서울');
INSERT INTO GR(NAME)VALUES('세종');
INSERT INTO GR(NAME)VALUES('울산');
INSERT INTO GR(NAME)VALUES('인천');
INSERT INTO GR(NAME)VALUES('전남');
INSERT INTO GR(NAME)VALUES('전북');
INSERT INTO GR(NAME)VALUES('제주');
INSERT INTO GR(NAME)VALUES('충남');
INSERT INTO GR(NAME)VALUES('충북');
-- 가보자고 테마 테이블 더미 데이터
INSERT INTO GT(NAME)VALUES('산');
INSERT INTO GT(NAME)VALUES('시장');
INSERT INTO GT(NAME)VALUES('테마파크');
INSERT INTO GT(NAME)VALUES('카페');
INSERT INTO GT(NAME)VALUES('문화');
-- 가보자고 지역 테마 연결 더미 데이터
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(1,1,'설악산', 'img/loc/강원/강원-설악산.jpg', '강원도', '역시 설악산은~ 굿굿', 0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(1,1,'죽도산','img/loc/강원/강원-죽도산.jpg','강원도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(1,2,'양양전통시장','img/loc/강원/강원-양양전통시장.jpg','강원도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(1,2,'갈미조개', 'img/loc/강원/강원-갈미조개.jpg', '강원도', '갈미조개 너무 맛있어요~', 0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(1,2,'중앙시장','img/loc/강원/강원-중앙시장.jpg','강원도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(1,3,'소양강스카이워크','img/loc/강원/강원-소양강스카이워크.jpg','강원도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(1,3,'BTS-버스정류장','img/loc/강원/강원-BTS버스정류장.jpg', '강원도', '강원도 너무 좋아요~', 0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(1,3,'지지리골 자작나무숲','img/loc/강원/강원-지지리골 자작나무숲.jpg','강원도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(1,4,'꽃게집', 'img/loc/강원/강원-꽃게집.jpg', '강원도', '인생 맛집 꽃게집~', 0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(1,5,'검룡소', 'img/loc/강원/강원-검룡소.jpg', '강원도', '검룡소 경치가 죽여줘욧~', 0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(1,5,'아르떼뮤지엄','img/loc/강원/강원-아르떼뮤지엄.jpg','강원도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(1,5,'아바이마을','img/loc/강원/강원-아바이마을.jpg','강원도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(1,5,'직탕폭포','img/loc/강원/강원-직탕폭포.jpg','강원도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(1,5,'평창동계올림픽기념관','img/loc/강원/강원-평창동계올림픽기념관.jpg','강원도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(1,5,'황지연못','img/loc/강원/강원-황지연못.jpg','강원도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(2,1,'감악산','img/loc/경기/경기-감악산.jpg','경기도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(2,2,'제일시장','img/loc/경기/경기-제일시장.jpg','경기도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(2,4,'카페 숨','img/loc/경기/경기-카페숨.jpg','경기도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(2,5,'한국민속촌','img/loc/경기/경기-한국민속촌.jpg','경기도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(3,1,'경남산','img/loc/경남/산 또는 바다.jpg','경상남도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(3,2,'경남시장','img/loc/경남/경남시장.png','경상남도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(3,3,'경남테마','img/loc/경남/경남테마.jpg','경상남도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(3,4,'경남카페','img/loc/경남/경남카페.jpg','경상남도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(3,5,'경남문화','img/loc/경남/경남문화.jpg','경상남도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(4,5,'경북문화','img/loc/경북/경북문화.jpg','경상북도','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(5,1,'무등산','img/loc/광주/무등산.jpg','광주','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(5,2,'1913 송정역시장','img/loc/광주/1913 송정역시장.jpg','광주','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(5,3,'패밀리랜드','img/loc/광주/패밀리랜드.jpg','광주','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(5,4,'베비에르','img/loc/광주/베비에르.jpg','광주','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(5,5,'광주향교','img/loc/광주/광주향교.jpg','광주','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(6,1,'앞산','img/loc/대구/대구-앞산.jpg','대구','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(6,2,'서문시장','img/loc/대구/대구-서문시장.jpg','대구','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(6,3,'이월드','img/loc/대구/대구-이월드.jpg','대구','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(6,4,'포켓','img/loc/대구/대구-포켓.jpg','대구','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(6,5,'성당못','img/loc/대구/대구-성당못.jpg','대구','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(7,1,'구봉산','img/loc/대전/대전-구봉산.jpg','대전','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(7,2,'태평시장','img/loc/대전/대전-태평시장.jpg','대전','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(7,3,'오월드','img/loc/대전/대전-오월드.jpg','대전','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(7,4,'두두당','img/loc/대전/대전-두두당.jpg','대전','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(7,5,'둔산선사','img/loc/대전/대전-둔산선사.jpg','대전','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,1,'하조대산','img/loc/부산/부산-하조대산.jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,2,'부산재첩국','img/loc/부산/부산-부산재첩국.jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,2,'순자네보양','img/loc/부산/부산-순자네보양.jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,2,'수안곰장어','img/loc/부산/부산-수안곰장어.jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,2,'포장마차거리','img/loc/부산/부산-포장마차거리.jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,3,'천문대','img/loc/부산/부산-천문대(테마파크).jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,3,'블루레일','img/loc/부산/부산-블루레일.jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,3,'다대포해수욕장','img/loc/부산/부산-다대포해수욕장.jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,3,'도자기미술관','img/loc/부산/부산-도자기미술관.jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,3,'더베이101','img/loc/부산/부산-더베이101.jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,4,'모모스커피','img/loc/부산/부산-모모스커피.jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,4,'블랙업커피','img/loc/부산/부산-블랙업커피.jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,5,'고석정','img/loc/부산/부산-고석정.jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,5,'남천동벚꽃축제','img/loc/부산/부산-남천동벚꽃축제.jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,5,'복천사','img/loc/부산/부산-복천사.jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,5,'연필뮤지엄','img/loc/부산/부산-연필뮤지엄.jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,5,'죽도정','img/loc/부산/부산-죽도정(문화).jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(8,5,'천곡황금박쥐동굴','img/loc/부산/부산-천곡황금박쥐동굴.jpg','부산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(9,1,'남산','img/loc/서울/남산.jpg','서울','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(9,1,'도봉산','img/loc/서울/서울-도봉산.jpg','서울','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(9,1,'북한산','img/loc/서울/서울-북한산.jpg','서울','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(9,2,'떡볶이타운','img/loc/서울/서울-떡볶이타운.jpg','서울','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(9,2,'족발골목','img/loc/서울/서울-장충동족발골목.jpg','서울','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(9,2,'파전골목','img/loc/서울/서울-파전골목.jpg','서울','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(9,3,'롯데월드','img/loc/서울/서울-롯데월드.jpg','서울','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(9,3,'서울식물원','img/loc/서울/서울-서울식물원.jpg','서울','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(9,3,'어린이대공원','img/loc/서울/서울-어린이대공원.jpg','서울','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(9,4,'연남동223-14','img/loc/서울/서울-그림카페.jpg','서울','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(9,4,'장프리고','img/loc/서울/서울-장프리고.jpg','서울','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(9,4,'자팡이','img/loc/서울/서울-자팡이.jpg','서울','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(9,5,'경복궁','img/loc/서울/서울-경복궁.jpg','서울','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(9,5,'세종대왕상','img/loc/서울/서울-세종대왕.jpg','서울','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(9,5,'이순신상','img/loc/서울/서울-이순신.jpg','서울','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(10,1,'세종 산','img/loc/세종/세종산.jpg','세종','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(11,2,'양지집','img/loc/울산/울산-양지집.jpg','울산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(10,3,'세종 테마파크1','img/loc/세종/세종테마파크.jpg','세종','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(10,3,'세종 테마파크2','img/loc/세종/세종테마파크2.jpg','세종','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(10,5,'세종 문화1','img/loc/세종/세종문화1.jpg','세종','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(10,5,'세종 문화2','img/loc/세종/세종문화2.jpg','세종','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(11,2,'울산시장','img/loc/울산/울산-울산시장.jpg','울산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(11,2,'청년조개','img/loc/울산/울산-청년조개.jpg','울산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(11,2,'초량갈비','img/loc/울산/울산-초량갈비.jpg','울산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(11,3,'플라워파크','img/loc/울산/울산-플라워파크.jpg','울산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(11,3,'서킷스피디움','img/loc/울산/울산-서킷스피디움.jpg','울산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(11,4,'양다방','img/loc/울산/울산-양다방.jpg','울산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(11,5,'노적봉폭포','img/loc/울산/울산-노적봉폭포.jpg','울산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(11,5,'역사평화의댐','img/loc/울산/울산-역사평화의댐.jpg','울산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(11,5,'연등축제','img/loc/울산/울산-연등축제.png','울산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(11,5,'울산항','img/loc/울산/울산-울산항.jpg','울산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(11,5,'인문학박물관','img/loc/울산/울산-인문학박물관.jpg','울산','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(12,1,'청량산','img/loc/인천/인천-청량산.jpg','인천','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(12,2,'신포시장','img/loc/인천/인천-신포시장.jpg','인천','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(12,3,'월미도','img/loc/인천/인천-월미도.jpg','인천','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(12,4,'포레스트아웃띵스','img/loc/인천/인천-포레스트아웃띵스.jpg','인천','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(12,5,'상륙작전기념관','img/loc/인천/인천-인천상륙작전기념관.jpg','인천','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(13,2,'전남 시장','img/loc/전남/전남시장.jpg','전남','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(13,5,'전남 바다','img/loc/전남/전남바다.jpg','전남','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(13,3,'전남 테마파크1','img/loc/전남/전남테마파크1.jpg','전남','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(13,3,'전남 테마파크2','img/loc/전남/전남테마파크2.jpg','전남','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(13,5,'전남 역사1','img/loc/전남/전남역사.jpg','전남','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(13,5,'전남 역사2','img/loc/전남/전남역사2.jpg','전남','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(14,3,'전북 테마파크1','img/loc/전북/전북테마파크.jpg','전북','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(14,3,'전북 테마파크2','img/loc/전북/전북테마파크2.jpg','전북','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(14,4,'전북 카페','img/loc/전북/전북카페.jpg','전북','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(14,5,'전북 문화','img/loc/전북/전북문화.jpg','전북','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(14,5,'전북 바다','img/loc/전북/전북바다.jpg','전북','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(15,3,'제주 테마파크1','img/loc/제주/제주테마파크.jpg','제주','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(15,3,'제주 테마파크2','img/loc/제주/테마파크.jpg','제주','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(15,5,'제주 문화1','img/loc/제주/제주문화.jpg','제주','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(15,5,'제주 문화2','img/loc/제주/제주문화2.jpg','제주','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(15,5,'제주 바다','img/loc/제주/제주바다.jpg','제주','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(15,5,'제주 축제','img/loc/제주/제주축제.jpg','제주','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(16,2,'충남 시장','img/loc/충남/충남시장.jpg','충남','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(16,3,'충남 테마파크','img/loc/충남/충남테마.jpg','충남','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(16,4,'충남 카페','img/loc/충남/충남카페.jpg','충남','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(16,5,'충남 바다','img/loc/충남/충남바다.jpg','충남','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(16,5,'충남 문화','img/loc/충남/충남문화.jpg','충남','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(17,1,'충북 산','img/loc/충북/충북산2.jpg','충북','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(17,2,'충북 시장','img/loc/충북/충북시장.jpg','충북','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(17,2,'충북 카페','img/loc/충북/충북카페.jpg','충북','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(17,3,'충북 테마파크','img/loc/충북/충북액티.jpg','충북','텍스트 영역',0);
INSERT INTO GP(GRID, GTID, NAME, IMG, STATE, TEXT, JJIMCOUNT)VALUES(17,5,'충북 문화','img/loc/충북/충북역사.jpg','충북','텍스트 영역',0);

-- 가봤다고 후기 게시판 더미데이터
INSERT INTO GABOWATDAGO(title, local, thema, image, content, address, de_address)
VALUES('후기1','서울','산','img/loc/강원/강원-설악산.jpg','1번후기게시글','서울시','서울시 강남구');
INSERT INTO GABOWATDAGO(title, local, thema, image, content, address, de_address)
VALUES('후기2','경기','시장','img/loc/강원/강원-설악산.jpg','2번후기게시글','경기','안산시 상록구');
INSERT INTO GABOWATDAGO(title, local, thema, image, content, address, de_address)
VALUES('후기3','인천','테마파크','img/loc/강원/강원-돼통령.jpg','3번후기게시글','인천','인천 연수구');
INSERT INTO GABOWATDAGO(title, local, thema, image, content, address, de_address)
VALUES('후기4','강원','카페','img/loc/강원/강원-돼통령.jpg','4번후기게시글','인천','인천 연수구');
INSERT INTO GABOWATDAGO(title, local, thema, image, content, address, de_address)
VALUES('후기5','경북','문화','img/loc/강원/강원-돼통령.jpg','5번후기게시글','인천','인천 연수구');
INSERT INTO GABOWATDAGO(title, local, thema, image, content, address, de_address)
VALUES('후기6','광주','산','img/loc/강원/강원-돼통령.jpg','6번후기게시글','인천','인천 연수구');
INSERT INTO GABOWATDAGO(title, local, thema, image, content, address, de_address)
VALUES('후기7','대구','시장','img/loc/강원/강원-돼통령.jpg','7번후기게시글','인천','인천 연수구');
INSERT INTO GABOWATDAGO(title, local, thema, image, content, address, de_address)
VALUES('후기8','부산','테마파크','img/loc/강원/강원-돼통령.jpg','8번후기게시글','인천','인천 연수구');
-- 가봤다고 후기 게시판 댓글 더미데이터
INSERT INTO CMT(gabowatdago_id, nickname, body)VALUES(1,'KIM', '후기 너무 좋아요');
INSERT INTO CMT(gabowatdago_id, nickname, body)VALUES(1,'JANG', '가보고싶어요');
INSERT INTO CMT(gabowatdago_id, nickname, body)VALUES(2,'KIM', '후기 너무 좋아요2');
INSERT INTO CMT(gabowatdago_id, nickname, body)VALUES(2,'JANG', '가보고싶어요2');
INSERT INTO CMT(gabowatdago_id, nickname, body)VALUES(3,'KIM', '후기 너무 좋아요3');
INSERT INTO CMT(gabowatdago_id, nickname, body)VALUES(3,'JANG', '가보고싶어요3');