-- 가보자고 지역 테이블 더미 데이터
INSERT INTO GR(NAME)VALUES('지역');
INSERT INTO GR(NAME)VALUES('강원');
INSERT INTO GR(NAME)VALUES('경기');
INSERT INTO GR(NAME)VALUES('경남');
INSERT INTO GR(NAME)VALUES('경북');
INSERT INTO GR(NAME)VALUES('광주');
INSERT INTO GR(NAME)VALUES('대구');
INSERT INTO GR(NAME)VALUES('대전');
INSERT INTO GR(NAME)VALUES('부산');
INSERT INTO GR(NAME)VALUES('서울');
INSERT INTO GR(NAME)VALUES('세종');
INSERT INTO GR(NAME)VALUES('울산');
INSERT INTO GR(NAME)VALUES('인천');
INSERT INTO GR(NAME)VALUES('전남');
INSERT INTO GR(NAME)VALUES('전북');
INSERT INTO GR(NAME)VALUES('제주');
INSERT INTO GR(NAME)VALUES('충남');
INSERT INTO GR(NAME)VALUES('충북');
-- 가보자고 테마 테이블 더미 데이터
INSERT INTO GT(NAME)VALUES('산');
INSERT INTO GT(NAME)VALUES('시장');
INSERT INTO GT(NAME)VALUES('테마파크');
INSERT INTO GT(NAME)VALUES('카페');
INSERT INTO GT(NAME)VALUES('문화');
-- 가보자고 지역 테마 연결 더미 데이터
INSERT INTO GRT(GRID, GTID, NAME)VALUES(1,1,'강원_산');
INSERT INTO GRT(GRID, GTID, NAME)VALUES(1,1,'강원_산2');
INSERT INTO GRT(GRID, GTID, NAME)VALUES(1,2,'강원_시장');
INSERT INTO GRT(GRID, GTID, NAME)VALUES(1,2,'강원_시장2');
INSERT INTO GRT(GRID, GTID, NAME)VALUES(1,3,'강원_테마파크');
INSERT INTO GRT(GRID, GTID, NAME)VALUES(1,3,'강원_테마파크2');
INSERT INTO GRT(GRID, GTID, NAME)VALUES(1,4,'강원_카페');
INSERT INTO GRT(GRID, GTID, NAME)VALUES(1,4,'강원_카페2');
INSERT INTO GRT(GRID, GTID, NAME)VALUES(1,4,'강원_카페3');
INSERT INTO GRT(GRID, GTID, NAME)VALUES(1,5,'강원_문화');
INSERT INTO GRT(GRID, GTID, NAME)VALUES(1,5,'강원_문화2');
INSERT INTO GRT(GRID, GTID, NAME)VALUES(1,5,'강원_문화3');
INSERT INTO GRT(GRID, GTID, NAME)VALUES(1,5,'강원_문화4');
-- 가보자고 장소 더미 데이터
INSERT INTO GP(GRID, GTID, NAME)VALUES(1,1,'설악산');
INSERT INTO GP(GRID, GTID, NAME)VALUES(1,1,'지지리골 자작나무숲');
INSERT INTO GP(GRID, GTID, NAME)VALUES(1,2,'양양 전통시장');
INSERT INTO GP(GRID, GTID, NAME)VALUES(1,2,'중앙시장');
INSERT INTO GP(GRID, GTID, NAME)VALUES(1,3,'BTS버스정류장');
INSERT INTO GP(GRID, GTID, NAME)VALUES(1,3,'아르떼뮤지엄');
INSERT INTO GP(GRID, GTID, NAME)VALUES(1,4,'갈미조개');
INSERT INTO GP(GRID, GTID, NAME)VALUES(1,4,'꽃게집');
INSERT INTO GP(GRID, GTID, NAME)VALUES(1,4,'돼통령');
INSERT INTO GP(GRID, GTID, NAME)VALUES(1,5,'검룡소');
INSERT INTO GP(GRID, GTID, NAME)VALUES(1,5,'소양강 스카이워크');
INSERT INTO GP(GRID, GTID, NAME)VALUES(1,5,'아바이 마을');
INSERT INTO GP(GRID, GTID, NAME)VALUES(1,5,'황지연못');
-- 가보자고 이미지 더미 데이터
INSERT INTO GI(GPID, NAME)VALUES(1,'/img/loc/강원/강원-설악산.jpg');
INSERT INTO GI(GPID, NAME)VALUES(2,'/img/loc/강원/강원-설악산.jpg');
INSERT INTO GI(GPID, NAME)VALUES(3,'/img/loc/강원/강원-설악산.jpg');

